Assignment 2: A2/Assignment2/Code/BstTest.cpp File Reference
BstTest.cpp File Reference
#include <iostream>
#include <vector>
#include <string>
#include "Bst.h"
Functions
void Collect (const int &x)
void ResetVisited ()
string VecToStr (const vector< int > &v)
void Assert (bool condition, const string &message)
void TestInsertAndSearch ()
void TestDuplicateInsert ()
void TestInOrderTraversal ()
void TestPreOrderTraversal ()
void TestPostOrderTraversal ()
void TestDeleteLeaf ()
void TestDeleteOneChild ()
void TestDeleteTwoChildren ()
void TestDeleteRoot ()
void TestDeleteTree ()
void TestCopyConstructor ()
void TestAssignmentOperator ()
void TestInvariantChecker ()
int main ()
Variables
vector< int > visited
Function Documentation
Assert()
void Assert (bool condition, const string & message)
Definition at line 40 of file BstTest.cpp.
{
    if (!condition)
    {
        cout << "[FAIL] " << message << endl;
    }
    else
    {
        cout << "[OK] " << message << endl;
    }
}
Referenced by TestAssignmentOperator(), TestCopyConstructor(), TestDeleteLeaf(), TestDeleteOneChild(), TestDeleteRoot(), TestDeleteTree(), TestDeleteTwoChildren(), TestDuplicateInsert(), TestInOrderTraversal(), TestInsertAndSearch(), TestPostOrderTraversal(), and TestPreOrderTraversal().
Collect()
void Collect (const int & x)
Definition at line 11 of file BstTest.cpp.
{
    visited.push_back(x);
}
References visited.
Referenced by TestDuplicateInsert(), TestInOrderTraversal(), TestPostOrderTraversal(), and TestPreOrderTraversal().
main()
int main ()
Definition at line 295 of file BstTest.cpp.
{
    TestInsertAndSearch();
    TestDuplicateInsert();
    TestInOrderTraversal();
    TestPreOrderTraversal();
    TestPostOrderTraversal();
    TestDeleteLeaf();
    TestDeleteOneChild();
    TestDeleteTwoChildren();
    TestDeleteRoot();
    TestDeleteTree();
    TestCopyConstructor();
    TestAssignmentOperator();
    TestInvariantChecker();
    cout << "\n=== ALL TESTS COMPLETE ===\n";
    return 0;
}
References TestAssignmentOperator(), TestCopyConstructor(), TestDeleteLeaf(), TestDeleteOneChild(), TestDeleteRoot(), TestDeleteTree(), TestDeleteTwoChildren(), TestDuplicateInsert(), TestInOrderTraversal(), TestInsertAndSearch(), TestInvariantChecker(), TestPostOrderTraversal(), and TestPreOrderTraversal().
ResetVisited()
void ResetVisited ()
Definition at line 17 of file BstTest.cpp.
{
    visited.clear();
}
References visited.
Referenced by TestDuplicateInsert(), TestInOrderTraversal(), TestPostOrderTraversal(), and TestPreOrderTraversal().
TestAssignmentOperator()
void TestAssignmentOperator ()
Definition at line 252 of file BstTest.cpp.
{
    cout << "\n=== TestAssignmentOperator ===\n";
    Bst<int> a, b;
    for (int x :
            {
                1, 2, 3
            })
    {
        a.Insert(x);
    }
    for (int x :
            {
                10, 20, 30
            })
    {
        b.Insert(x);
    }
    b = a;  // assignment
    Assert(b.Search(1) && b.Search(3), "Assigned tree has copied values");
    a.DeleteNode(1);
    Assert(b.Search(1), "Deep copy unaffected by modifications");
}
References Assert(), Bst< T >::DeleteNode(), Bst< T >::Insert(), Bst< T >::operator=(), and Bst< T >::Search().
Referenced by main().
TestCopyConstructor()
void TestCopyConstructor ()
Definition at line 228 of file BstTest.cpp.
{
    cout << "\n=== TestCopyConstructor ===\n";
    Bst<int> tree;
    for (int i :
            {
                5, 3, 7, 1, 9
            })
    {
        tree.Insert(i);
    }
    Bst<int> copy(tree);
    Assert(copy.Search(3), "Copy contains same values");
    Assert(copy.Search(9), "Copy contains same values");
    // Modify original, ensure copy unchanged
    tree.DeleteNode(3);
    Assert(copy.Search(3), "Deep copy unaffected by original's changes");
}
References Assert(), Bst< T >::Bst(), Bst< T >::DeleteNode(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestDeleteLeaf()
void TestDeleteLeaf ()
Definition at line 146 of file BstTest.cpp.
{
    cout << "\n=== TestDeleteLeaf ===\n";
    Bst<int> tree;
    tree.Insert(5);
    tree.Insert(3);
    tree.Insert(7);
    tree.DeleteNode(3);
    Assert(!tree.Search(3), "Leaf deletion removes node");
}
References Assert(), Bst< T >::DeleteNode(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestDeleteOneChild()
void TestDeleteOneChild ()
Definition at line 161 of file BstTest.cpp.
{
    cout << "\n=== TestDeleteOneChild ===\n";
    Bst<int> tree;
    tree.Insert(5);
    tree.Insert(7);
    tree.Insert(9);  // child of 7
    tree.DeleteNode(7);
    Assert(!tree.Search(7), "Node with one child deleted");
    Assert(tree.Search(9), "Child promoted correctly");
}
References Assert(), Bst< T >::DeleteNode(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestDeleteRoot()
void TestDeleteRoot ()
Definition at line 194 of file BstTest.cpp.
{
    cout << "\n=== TestDeleteRoot ===\n";
    Bst<int> tree;
    tree.Insert(10);
    tree.Insert(5);
    tree.Insert(15);
    tree.DeleteNode(10);
    Assert(!tree.Search(10), "Root deleted");
}
References Assert(), Bst< T >::DeleteNode(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestDeleteTree()
void TestDeleteTree ()
Definition at line 209 of file BstTest.cpp.
{
    cout << "\n=== TestDeleteTree ===\n";
    Bst<int> tree;
    for (int i = 0; i < 10; i++)
    {
        tree.Insert(i);
    }
    tree.DeleteTree();
    for (int i = 0; i < 10; i++)
    {
        Assert(!tree.Search(i), "Tree empty after DeleteTree");
    }
}
References Assert(), Bst< T >::DeleteTree(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestDeleteTwoChildren()
void TestDeleteTwoChildren ()
Definition at line 177 of file BstTest.cpp.
{
    cout << "\n=== TestDeleteTwoChildren ===\n";
    Bst<int> tree;
    int vals[] = {50, 30, 70, 20, 40, 60, 80};
    for (int x : vals)
    {
        tree.Insert(x);
    }
    tree.DeleteNode(50);  // root with two children
    Assert(!tree.Search(50), "Node with two children deleted");
}
References Assert(), Bst< T >::DeleteNode(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestDuplicateInsert()
void TestDuplicateInsert ()
Definition at line 71 of file BstTest.cpp.
{
    cout << "\n=== TestDuplicateInsert ===\n";
    Bst<int> tree;
    tree.Insert(5);
    tree.Insert(5); // duplicate should be ignored
    ResetVisited();
    tree.InOrder(Collect);
    Assert(visited.size() == 1, "Duplicate insertion ignored");
}
References Assert(), Collect(), Bst< T >::InOrder(), Bst< T >::Insert(), ResetVisited(), and visited.
Referenced by main().
TestInOrderTraversal()
void TestInOrderTraversal ()
Definition at line 86 of file BstTest.cpp.
{
    cout << "\n=== TestInOrderTraversal ===\n";
    Bst<int> tree;
    int vals[] = {5, 3, 7, 1, 9, 8};
    for (int x : vals)
    {
        tree.Insert(x);
    }
    ResetVisited();
    tree.InOrder(Collect);
    vector<int> expected = {1, 3, 5, 7, 8, 9};
    Assert(visited == expected,
           string("InOrder = ") + VecToStr(visited));
}
References Assert(), Collect(), Bst< T >::InOrder(), Bst< T >::Insert(), ResetVisited(), VecToStr(), and visited.
Referenced by main().
TestInsertAndSearch()
void TestInsertAndSearch ()
Definition at line 53 of file BstTest.cpp.
{
    cout << "\n=== TestInsertAndSearch ===\n";
    Bst<int> tree;
    tree.Insert(5);
    tree.Insert(3);
    tree.Insert(7);
    tree.Insert(1);
    tree.Insert(9);
    Assert(tree.Search(5), "Search root");
    Assert(tree.Search(1), "Search leftmost");
    Assert(tree.Search(9), "Search rightmost");
    Assert(!tree.Search(4), "Search missing value");
}
References Assert(), Bst< T >::Insert(), and Bst< T >::Search().
Referenced by main().
TestInvariantChecker()
void TestInvariantChecker ()
Definition at line 281 of file BstTest.cpp.
{
    cout << "\n=== TestInvariantChecker ===\n";
    Bst<int> tree;
    for (int x :
            {
                10, 5, 15, 2, 7
            })
    {
        tree.Insert(x);
    }
}
References Bst< T >::Insert().
Referenced by main().
TestPostOrderTraversal()
void TestPostOrderTraversal ()
Definition at line 126 of file BstTest.cpp.
{
    cout << "\n=== TestPostOrderTraversal ===\n";
    Bst<int> tree;
    int vals[] = {5, 3, 7, 1, 9, 8};
    for (int x : vals)
    {
        tree.Insert(x);
    }
    ResetVisited();
    tree.PostOrder(Collect);
    vector<int> expected = {1, 3, 8, 9, 7, 5};
    Assert(visited == expected,
           string("PostOrder = ") + VecToStr(visited));
}
References Assert(), Collect(), Bst< T >::Insert(), Bst< T >::PostOrder(), ResetVisited(), VecToStr(), and visited.
Referenced by main().
TestPreOrderTraversal()
void TestPreOrderTraversal ()
Definition at line 106 of file BstTest.cpp.
{
    cout << "\n=== TestPreOrderTraversal ===\n";
    Bst<int> tree;
    int vals[] = {5, 3, 7, 1, 9, 8};
    for (int x : vals)
    {
        tree.Insert(x);
    }
    ResetVisited();
    tree.PreOrder(Collect);
    vector<int> expected = {5, 3, 1, 7, 9, 8};
    Assert(visited == expected,
           string("PreOrder = ") + VecToStr(visited));
}
References Assert(), Collect(), Bst< T >::Insert(), Bst< T >::PreOrder(), ResetVisited(), VecToStr(), and visited.
Referenced by main().
VecToStr()
string VecToStr (const vector< int > & v)
Definition at line 24 of file BstTest.cpp.
{
    string out = "{ ";
    for (size_t i = 0; i < v.size(); ++i)
    {
        out += to_string(v[i]);
        if (i + 1 < v.size())
        {
            out += ", ";
        }
    }
    out += " }";
    return out;
}
Referenced by TestInOrderTraversal(), TestPostOrderTraversal(), and TestPreOrderTraversal().
Variable Documentation
visited
vector<int> visited
Definition at line 8 of file BstTest.cpp.
Referenced by Collect(), ResetVisited(), TestDuplicateInsert(), TestInOrderTraversal(), TestPostOrderTraversal(), and TestPreOrderTraversal().