Assignment 2: A2/Assignment2/Code/Date.cpp File Reference
Date.cpp File Reference
#include "Date.h"
#include <stdexcept>
Functions
istream & operator>> (istream &input, Date &date)
Extracts a Date from an input stream.
ostream & operator<< (ostream &os, const Date &date)
Inserts a formatted Date into an output stream.
Variables
static const string MonthNames [12]
Function Documentation
operator<<()
ostream & operator<< (ostream & os, const Date & date)
Inserts a formatted Date into an output stream.
Output format:
day MonthName year
// Example: 3 March 2025
Parameters
os Stream to write to.
date Date object to output.
Returns
Reference to the output stream.
Definition at line 108 of file Date.cpp.
{
    os << date.GetDay() << " "
       << MonthNames[date.GetMonth() - 1] << " "
       << date.GetYear();
    return os;
}
References Date::GetDay(), Date::GetMonth(), Date::GetYear(), and MonthNames.
operator>>()
istream & operator>> (istream & input, Date & date)
Extracts a Date from an input stream.
Expected input format:
day month year
Parameters
input Stream to read from.
date Date object to populate.
Returns
Reference to the input stream.
Definition at line 98 of file Date.cpp.
{
    int d, m, y;
    input >> d >> m >> y;
    date.SetDate(d, m, y);
    return input;
}
References Date::SetDate().
Referenced by main().
Variable Documentation
MonthNames
const string MonthNames[12] static
Initial value:
=
{
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
}
Definition at line 7 of file Date.cpp.
{
    "January","February","March","April","May","June",
    "July","August","September","October","November","December"
};
Referenced by Date::GetMonthNames(), and operator<<().