Assignment 2: A2/Assignment2/Code/Time.h File Reference
Time.h File Reference
#include <iostream>
Classes
class Time
Represents a specific time of day in hours and minutes.
Functions
ostream & operator<< (ostream &out, const Time &t)
Outputs a Time object to a stream.
istream & operator>> (istream &in, Time &t)
Inputs a Time object from a stream.
Function Documentation
operator<<()
ostream & operator<< (ostream & out, const Time & t)
Outputs a Time object to a stream.
Parameters
out The output stream.
t The Time object to output.
Returns
Reference to the output stream.
Definition at line 56 of file Time.cpp.
{
    os << setw(2) << setfill('0') << t.GetHours() << ":"
       << setw(2) << setfill('0') << t.GetMinutes();
    return os;
}
References Time::GetHours(), and Time::GetMinutes().
operator>>()
istream & operator>> (istream & in, Time & t)
Inputs a Time object from a stream.
Parameters
in The input stream.
t The Time object to populate.
Returns
Reference to the input stream.
Definition at line 64 of file Time.cpp.
{
    int h, m;
    char colon;
    input >> h >> colon >> m;  // Expect format HH:MM
    t.SetTime(h, m);           // Validate and store
    return input;
}
References Time::SetTime().