Assignment 2: A2/Assignment2/Code/VectorTest2.cpp File Reference
VectorTest2.cpp File Reference
#include "Vector.h"
#include "Date.h"
#include <iostream>
#include <string>
Functions
int testIntVec (Vector< int > &vec)
int testDateVecValue (Vector< Date > vec)
int testDateVecRef (Vector< Date > &vec)
template<typename T >
void printVec (const Vector< T > &vec, const string &name)
int main ()
Function Documentation
main()
int main ()
Definition at line 25 of file VectorTest2.cpp.
{
    Vector<int> intVec;
    Vector<Date> dateVec;
    // Run tests
    testIntVec(intVec);
    testDateVecValue(dateVec);   // pass by value (copy)
    testDateVecRef(dateVec);     // pass by reference (same object)
    return 0;
}
References testDateVecRef(), testDateVecValue(), and testIntVec().
printVec()
template<typename T > void printVec (const Vector< T > & vec, const string & name)
Definition at line 15 of file VectorTest2.cpp.
{
    cout << "Contents of " << name << " (size: " << vec.GetSize() << "):" << endl;
    for (int i = 0; i < vec.GetSize(); ++i)
    {
        cout << "  [" << i << "] " << vec[i] << endl;
    }
    cout << endl;
}
Referenced by testDateVecRef(), testDateVecValue(), and testIntVec().
testDateVecRef()
int testDateVecRef (Vector< Date > & vec)
Definition at line 88 of file VectorTest2.cpp.
{
    cout << "\nDate Vector Test (by reference)" << endl;
    vec.Insert(vec.GetSize(), Date(2, 2, 2025));
    vec.Insert(vec.GetSize(), Date(3, 3, 2025));
    printVec(vec, "dateVec (by reference)");
    vec.Delete(0); // delete first element
    printVec(vec, "dateVec after Delete index 0");
    cout << "Element at index 0: " << vec[0] << endl;
    return 0;
}
References Date::Date(), Vector< T >::Delete(), Vector< T >::GetSize(), Vector< T >::Insert(), Vector< T >::operator[](), and printVec().
Referenced by main().
testDateVecValue()
int testDateVecValue (Vector< Date > vec)
Definition at line 69 of file VectorTest2.cpp.
{
    cout << "\nDate Vector Test (by value)" << endl;
    vec.Insert(vec.GetSize(), Date(1, 1, 2025));
    vec.Insert(vec.GetSize(), Date(15, 3, 2025));
    vec.Insert(vec.GetSize(), Date(31, 12, 2025));
    printVec(vec, "dateVec (by value)");
    // Delete one element
    vec.Delete(1);
    printVec(vec, "dateVec after Delete index 1");
    cout << "Element at index 0: " << vec[0] << endl;
    return 0;
}
References Date::Date(), Vector< T >::Delete(), Vector< T >::GetSize(), Vector< T >::Insert(), Vector< T >::operator[](), and printVec().
Referenced by main().
testIntVec()
int testIntVec (Vector< int > & vec)
Definition at line 38 of file VectorTest2.cpp.
{
    cout << "\nInteger Vector Test" << endl;
    // Insert elements at the end
    for (int i = 1; i <= 5; i++)
    {
        vec.Insert(vec.GetSize(), i);
    }
    printVec(vec, "intVec after Insert");
    // Delete first element
    vec.Delete(0);
    printVec(vec, "intVec after Delete index 0");
    // Access operator
    cout << "Element at index 1: " << vec[1] << endl;
    // Copy constructor
    Vector<int> copyVec(vec);
    printVec(copyVec, "copyVec");
    // Assignment operator
    Vector<int> assignedVec;
    assignedVec = vec;
    printVec(assignedVec, "assignedVec");
    return 0;
}
References Vector< T >::Delete(), Vector< T >::GetSize(), Vector< T >::Insert(), Vector< T >::operator=(), Vector< T >::operator[](), printVec(), and Vector< T >::Vector().
Referenced by main().