Assignment 2: A2/Assignment2/Code/VectorTest.cpp File Reference
VectorTest.cpp File Reference
#include "EncapVect.h"
#include <iostream>
Functions
void DefaultTest ()
void InsertTest ()
void DeleteTest ()
void AccessTest ()
void CopyTest ()
void AssignTest ()
int main ()
Variables
Vector< int > myVector
Function Documentation
AccessTest()
void AccessTest ()
Definition at line 73 of file VectorTest.cpp.
{
    cout << "Access operator test" << endl;
    cout << "Element at index 0: " << myVector[0] << endl << endl;
}
References myVector, and Vector< T >::operator[]().
Referenced by main().
AssignTest()
void AssignTest ()
Definition at line 91 of file VectorTest.cpp.
{
    cout << "Assignment operator test" << endl;
    Vector<int> assignedVector;
    assignedVector = myVector;
    cout << "Assigned vector elements: ";
    for(int i = 0; i < assignedVector.GetSize(); i++)
    {
        cout << assignedVector[i] << " ";
    }
    cout << endl << endl;
}
References Vector< T >::GetSize(), myVector, and Vector< T >::operator[]().
Referenced by main().
CopyTest()
void CopyTest ()
Definition at line 79 of file VectorTest.cpp.
{
    cout << "Copy constructor test" << endl;
    Vector<int> copiedVector(myVector);
    cout << "Copied vector elements: ";
    for(int i = 0; i < copiedVector.GetSize(); i++)
    {
        cout << copiedVector[i] << " ";
    }
    cout << endl << endl;
}
References Vector< T >::GetSize(), myVector, and Vector< T >::operator[]().
Referenced by main().
DefaultTest()
void DefaultTest ()
Definition at line 28 of file VectorTest.cpp.
{
    cout << "Default Constructor, initial size: " << myVector.GetSize() << endl << endl;
}
References Vector< T >::GetSize(), and myVector.
Referenced by main().
DeleteTest()
void DeleteTest ()
Definition at line 61 of file VectorTest.cpp.
{
    cout << "Delete test" << endl;
    myVector.Delete(0); // Delete element at index 0
    cout << "After deleting index 0: ";
    for(int i = 0; i < myVector.GetSize(); i++)
    {
        cout << myVector[i] << " ";
    }
    cout << endl << endl;
}
References Vector< T >::Delete(), Vector< T >::GetSize(), myVector, and Vector< T >::operator[]().
Referenced by main().
InsertTest()
void InsertTest ()
Definition at line 33 of file VectorTest.cpp.
{
    cout << "Insert test" << endl;
    // Add elements using Insert at the end
    myVector.Insert(myVector.GetSize(), 1);
    myVector.Insert(myVector.GetSize(), 2);
    myVector.Insert(myVector.GetSize(), 3);
    myVector.Insert(myVector.GetSize(), 4);
    myVector.Insert(myVector.GetSize(), 5);
    cout << "Size after inserting: " << myVector.GetSize() << endl;
    cout << "Elements: ";
    for(int i = 0; i < myVector.GetSize(); i++)
    {
        cout << myVector[i] << " ";
    }
    cout << endl;
    // Insert 99 at index 1
    myVector.Insert(1, 99);
    cout << "After inserting 99 at index 1: ";
    for(int i = 0; i < myVector.GetSize(); i++)
    {
        cout << myVector[i] << " ";
    }
    cout << endl << endl;
}
References Vector< T >::GetSize(), Vector< T >::Insert(), myVector, and Vector< T >::operator[]().
Referenced by main().
main()
int main ()
Definition at line 16 of file VectorTest.cpp.
{
    DefaultTest();
    InsertTest();
    DeleteTest();
    AccessTest();
    CopyTest();
    AssignTest();
    return 0;
}
References AccessTest(), AssignTest(), CopyTest(), DefaultTest(), DeleteTest(), and InsertTest().
Variable Documentation
myVector
Vector<int> myVector
Definition at line 7 of file VectorTest.cpp.
Referenced by AccessTest(), AssignTest(), CopyTest(), DefaultTest(), DeleteTest(), and InsertTest().