Assignment 2: A2/Assignment2/Code/WeatherRec.h File Reference
WeatherRec.h File Reference
#include "Date.h"
#include "Time.h"
#include "DateTimeKey.h"
#include <iostream>
Classes
class WeatherRec
Represents a single weather observation.
Functions
ostream & operator<< (ostream &os, const WeatherRec &wr)
Stream insertion operator for WeatherRec.
Function Documentation
operator<<()
ostream & operator<< (ostream & os, const WeatherRec & wr)
Stream insertion operator for WeatherRec.
Outputs the record in a readable format for debugging, logs, and text-based displays.
Parameters
os Output stream.
wr WeatherRec instance to print.
Returns
Reference to the modified output stream.
Definition at line 105 of file WeatherRec.cpp.
{
    os << wr.GetDate() << " " << wr.GetTime()
       << " | Speed: " << wr.GetSpeed() << " m/s"
       << " | Solar Radiation: " << wr.GetSolarRad() << " W/m^2"
       << " | Air Temp: " << wr.GetAmbAirTemp() << " C";
    return os;
}
References WeatherRec::GetAmbAirTemp(), WeatherRec::GetDate(), WeatherRec::GetSolarRad(), WeatherRec::GetSpeed(), and WeatherRec::GetTime().