Assignment 2: A2/Assignment2/Code/WeatherLog.cpp File Reference
WeatherLog.cpp File Reference
#include "WeatherLog.h"
#include <iostream>
#include <fstream>
#include <cmath>
#include <string>
#include <sstream>
#include <stdexcept>
Functions
bool IsValidNumber (const string &s)
void InsertMiddle (Bst< RecNode > &bst, Vector< RecNode > &nodes, int start, int end)
static void CollectRecNode (const RecNode &node)
float sPCC (const Vector< float > &X, const Vector< float > &Y)
float MeanAbsoluteDeviation (const Vector< float > &data, float mean)
Variables
static Vector< RecNode > * g_traverseBuffer = nullptr
Function Documentation
CollectRecNode()
static void CollectRecNode (const RecNode & node) static
Definition at line 112 of file WeatherLog.cpp.
{
    if (g_traverseBuffer != nullptr)
    {
        g_traverseBuffer->Insert(g_traverseBuffer->GetSize(), node);
    }
}
References g_traverseBuffer, Vector< T >::GetSize(), and Vector< T >::Insert().
Referenced by WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), and WeatherLog::DisplaySpeedTempSolarRadWithMAD().
InsertMiddle()
void InsertMiddle (Bst< RecNode > & bst, Vector< RecNode > & nodes, int start, int end)
Definition at line 93 of file WeatherLog.cpp.
{
    if(start > end)
    {
        return;
    }
    int mid = (start + end) / 2;
    bst.Insert(nodes[mid]);
    InsertMiddle(bst, nodes, start, mid - 1);
    InsertMiddle(bst, nodes, mid + 1, end);
}
References Bst< T >::Insert(), InsertMiddle(), and Vector< T >::operator[]().
Referenced by InsertMiddle(), and WeatherLog::LoadData().
IsValidNumber()
bool IsValidNumber (const string & s)
Definition at line 24 of file WeatherLog.cpp.
{
    if(s.empty())
    {
        return false;
    }
    // Convert to lowercase to handle "NA", "N/A", "---", "-9999"
    string lower;
    for(size_t i = 0; i < s.size(); ++i)
    {
        char c = s[i];
        if(c >= 'A' && c <= 'Z')
        {
            c = c - 'A' + 'a';
        }
        lower += c;
    }
    if(lower == "na" || lower == "n/a" || lower == "---" || lower == "-9999")
    {
        return false;
    }
    bool hasDigit = false, hasDot = false, hasE = false;
    for(size_t i = 0; i < s.size(); ++i)
    {
        char c = s[i];
        if(c >= '0' && c <= '9')
        {
            hasDigit = true;
        }
        else if(c == '.')
        {
            if(hasDot || hasE)
            {
                return false;
            }
            hasDot = true;
        }
        else if(c == 'e' || c == 'E')
        {
            if(hasE || !hasDigit || i + 1 == s.size())
            {
                return false;
            }
            hasE = true;
            hasDigit = false;
        }
        else if(c == '+' || c == '-')
        {
            if (i > 0 && s[i - 1] != 'e' && s[i - 1] != 'E')
            {
                return false;
            }
        }
        else
        {
            return false;
        }
    }
    return hasDigit;
}
Referenced by WeatherLog::LoadData().
MeanAbsoluteDeviation()
float MeanAbsoluteDeviation (const Vector< float > & data, float mean)
Definition at line 479 of file WeatherLog.cpp.
{
    float mad = 0.0f;
    int n = data.GetSize();
    for(int i = 0; i < n; i++)
    {
        mad += fabs(data[i] - mean);
    }
    return (n > 0) ? (mad / n) : 0.0f;
}
References Vector< T >::GetSize(), and Vector< T >::operator[]().
Referenced by WeatherLog::DisplaySpeedTempSolarRadWithMAD().
sPCC()
float sPCC (const Vector< float > & X, const Vector< float > & Y)
Definition at line 400 of file WeatherLog.cpp.
{
    int n = X.GetSize();
    if(n == 0 || n != Y.GetSize())
    {
        return 0.0f;
    }
    float sumX = 0.0f, sumY = 0.0f;
    for(int i = 0; i < n; i++)
    {
        sumX += X[i];
        sumY += Y[i];
    }
    float meanX = sumX / n;
    float meanY = sumY / n;
    float numerator = 0.0f, denomX = 0.0f, denomY = 0.0f;
    for(int i = 0; i < n; i++)
    {
        float dx = X[i] - meanX;
        float dy = Y[i] - meanY;
        numerator += dx * dy;
        denomX += dx * dx;
        denomY += dy * dy;
    }
    if(denomX == 0 || denomY == 0)
    {
        return 0.0f;
    }
    return numerator / sqrt(denomX * denomY);
}
References Vector< T >::GetSize(), and Vector< T >::operator[]().
Referenced by WeatherLog::DisplaySPCC().
Variable Documentation
g_traverseBuffer
Vector<RecNode>* g_traverseBuffer = nullptr static
Definition at line 109 of file WeatherLog.cpp.
Referenced by CollectRecNode(), WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), and WeatherLog::DisplaySpeedTempSolarRadWithMAD().