Assignment 2: Time Class Reference
Time Class Reference
Represents a specific time of day in hours and minutes.
#include <Time.h>
Public Member Functions
Time ()
Default constructor. Initializes time to 00:00.
Time (int hour, int minutes)
Parameterized constructor.
int GetHours () const
Retrieves the hour component of the time.
int GetMinutes () const
Retrieves the minute component of the time.
void SetTime (int hour, int minutes)
Sets the time.
Private Attributes
int m_hour
int m_minutes
Detailed Description
Represents a specific time of day in hours and minutes.
Provides methods to retrieve and set time, and supports I/O streaming.
Definition at line 15 of file Time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
Default constructor. Initializes time to 00:00.
Definition at line 8 of file Time.cpp.
{
    m_hour = 0;
    m_minutes = 0;
}
References m_hour, and m_minutes.
Time() [2/2]
Time::Time (int hour, int minutes)
Parameterized constructor.
Parameters
hour The hour component (0-23).
minutes The minute component (0-59).
Definition at line 15 of file Time.cpp.
{
    SetTime(hour, minutes);
}
References SetTime().
Referenced by WeatherLog::LoadData(), TestEquality(), and TestOrdering().
Member Function Documentation
GetHours()
int Time::GetHours () const
Retrieves the hour component of the time.
Returns
The hour (0-23).
Definition at line 21 of file Time.cpp.
{
    return m_hour;
}
References m_hour.
Referenced by DateTimeKey::DateTimeKey(), and operator<<().
GetMinutes()
int Time::GetMinutes () const
Retrieves the minute component of the time.
Returns
The minutes (0-59).
Definition at line 27 of file Time.cpp.
{
    return m_minutes;
}
References m_minutes.
Referenced by DateTimeKey::DateTimeKey(), and operator<<().
SetTime()
void Time::SetTime (int hour, int minutes)
Sets the time.
Parameters
hour The hour to set (0-23).
minutes The minutes to set (0-59).
Definition at line 34 of file Time.cpp.
{
    if(hour >= 0 && hour < 24)
    {
        m_hour = hour;
    }
    else
    {
        m_hour = 0;
    }
    if(minutes >= 0 && minutes < 60)
    {
        m_minutes = minutes;
    }
    else
    {
        m_minutes = 0;
    }
}
References m_hour, and m_minutes.
Referenced by operator>>(), and Time().
Member Data Documentation
m_hour
int Time::m_hour private
Hour component (0-23)
Definition at line 50 of file Time.h.
Referenced by GetHours(), SetTime(), and Time().
m_minutes
int Time::m_minutes private
Minute component (0-59)
Definition at line 51 of file Time.h.
Referenced by GetMinutes(), SetTime(), and Time().
The documentation for this class was generated from the following files:
A2/Assignment2/Code/Time.h
A2/Assignment2/Code/Time.cpp