Assignment 2: Bst< T > Class Template Reference
Bst< T > Class Template Reference
A templated Binary Search Tree (BST) implementation.
#include <Bst.h>
Classes
struct Node
Represents a single BST node.
Public Member Functions
Bst ()
Constructs an empty BST.
~Bst ()
Destructor.
Bst (const Bst &other)
Copy constructor.
Bst & operator= (const Bst &other)
Copy assignment operator.
void Insert (const T &value)
Inserts a value into the BST.
bool Search (const T &value) const
Searches for a value in the BST.
void DeleteTree ()
Removes all nodes in the tree and resets it to empty.
void DeleteNode (const T &value)
Deletes a node containing the specified value.
void InOrder (void(*func)(const T &)) const
Performs an in-order traversal.
void PreOrder (void(*func)(const T &)) const
Performs a pre-order traversal.
void PostOrder (void(*func)(const T &)) const
Performs a post-order traversal.
Private Member Functions
Node * insert (Node *node, const T &value)
Recursive insert helper.
bool search (Node *node, const T &value) const
Recursive search helper.
void inOrder (const Node *node, void(*func)(const T &)) const
Recursive in-order traversal helper.
void preOrder (const Node *node, void(*func)(const T &)) const
Recursive pre-order traversal helper.
void postOrder (const Node *node, void(*func)(const T &)) const
Recursive post-order traversal helper.
void deleteTree (Node *node)
Recursive destroy helper.
Node * deleteNode (Node *node, const T &value)
Recursive delete-node helper.
Node * copyTree (Node *node)
Recursively clones a subtree.
Private Attributes
Node * root
Pointer to the root of the BST.
Detailed Description
template<class T>
class Bst< T >
A templated Binary Search Tree (BST) implementation.
This class stores elements in a binary search tree structure, allowing fast insertion, lookup, deletion, and depth-first traversals. Values stored in the tree must support the <, >, and == comparison operators.
Supported operations:
Insert a new value
Search for a value
Delete a specific value
Clear the entire tree
In-order, pre-order, and post-order traversal
Template Parameters
T Type of elements stored in the BST.
Definition at line 26 of file Bst.h.
Constructor & Destructor Documentation
Bst() [1/2]
template<class T > Bst< T >::Bst ()
Constructs an empty BST.
Definition at line 190 of file Bst.h.
{
    root = nullptr;
}
References Bst< T >::root.
Referenced by WeatherLog::LoadData().
~Bst()
template<class T > Bst< T >::~Bst ()
Destructor.
Recursively deallocates all nodes in the tree.
Definition at line 196 of file Bst.h.
{
    deleteTree(root);
    root = nullptr;
}
References Bst< T >::deleteTree(), and Bst< T >::root.
Bst() [2/2]
template<class T > Bst< T >::Bst (const Bst< T > & other)
Copy constructor.
Creates a deep copy of another BST.
Parameters
other Tree to copy.
Definition at line 202 of file Bst.h.
{
    root = copyTree(other.root);
}
References Bst< T >::copyTree(), and Bst< T >::root.
Referenced by TestCopyConstructor().
Member Function Documentation
copyTree()
template<class T > Bst< T >::Node * Bst< T >::copyTree (Node * node) private
Recursively clones a subtree.
Parameters
node Root of the subtree to clone.
Returns
New subtree root.
Definition at line 208 of file Bst.h.
{
    if (!node)
    {
        return nullptr;
    }
    Node* newNode = new Node{node->data, nullptr, nullptr};
    newNode->left = copyTree(node->left);
    newNode->right = copyTree(node->right);
    return newNode;
}
References Bst< T >::copyTree().
Referenced by Bst< T >::Bst(), Bst< T >::copyTree(), and Bst< T >::operator=().
DeleteNode()
template<class T > void Bst< T >::DeleteNode (const T & value)
Deletes a node containing the specified value.
If the value does not exist, no changes are made.
Parameters
value The value to remove.
Definition at line 301 of file Bst.h.
{
    root = deleteNode(root, value);
}
References Bst< T >::deleteNode(), and Bst< T >::root.
Referenced by TestAssignmentOperator(), TestCopyConstructor(), TestDeleteLeaf(), TestDeleteOneChild(), TestDeleteRoot(), and TestDeleteTwoChildren().
deleteNode()
template<class T > Bst< T >::Node * Bst< T >::deleteNode (Node * node, const T & value) private
Recursive delete-node helper.
Parameters
node Current subtree root.
value Value to remove.
Returns
Updated subtree root pointer.
Definition at line 307 of file Bst.h.
{
    if (node == nullptr)
    {
        return nullptr;
    }
    if (value < node->data)
    {
        node->left = deleteNode(node->left, value);
    }
    else if (value > node->data)
    {
        node->right = deleteNode(node->right, value);
    }
    else
    {
        // Case 1: Leaf
        if (node->left == nullptr && node->right == nullptr)
        {
            delete node;
            node = nullptr;
        }
        // Case 2: One child
        else if (node->left == nullptr)
        {
            Node* temp = node->right;
            delete node;
            node = temp;
        }
        else if (node->right == nullptr)
        {
            Node* temp = node->left;
            delete node;
            node = temp;
        }
        // Case 3: Two children
        else
        {
            Node* successor = node->right;
            while (successor->left != nullptr)
            {
                successor = successor->left;
            }
            node->data = successor->data;
            node->right = deleteNode(node->right, successor->data);
        }
    }
    return node;
}
References Bst< T >::deleteNode().
Referenced by Bst< T >::DeleteNode(), and Bst< T >::deleteNode().
DeleteTree()
template<class T > void Bst< T >::DeleteTree ()
Removes all nodes in the tree and resets it to empty.
Definition at line 283 of file Bst.h.
{
    deleteTree(root);
    root = nullptr;
}
References Bst< T >::deleteTree(), and Bst< T >::root.
Referenced by TestDeleteTree().
deleteTree()
template<class T > void Bst< T >::deleteTree (Node * node) private
Recursive destroy helper.
Parameters
node Subtree root to delete.
Definition at line 290 of file Bst.h.
{
    if (node)
    {
        deleteTree(node->left);
        deleteTree(node->right);
        delete node;
    }
}
References Bst< T >::deleteTree().
Referenced by Bst< T >::DeleteTree(), Bst< T >::deleteTree(), Bst< T >::operator=(), and Bst< T >::~Bst().
inOrder()
template<class T > void Bst< T >::inOrder (const Node * node, void(*)(const T &) func) const private
Recursive in-order traversal helper.
Definition at line 365 of file Bst.h.
{
    if (node)
    {
        inOrder(node->left, func);
        func(node->data);
        inOrder(node->right, func);
    }
}
References Bst< T >::inOrder().
Referenced by Bst< T >::inOrder(), and Bst< T >::InOrder().
InOrder()
template<class T > void Bst< T >::InOrder (void(*)(const T &) func) const
Performs an in-order traversal.
Order: Left Root Right Produces sorted output if the BST contains no duplicates.
Parameters
func Function applied to each visited node's value.
Definition at line 359 of file Bst.h.
{
    inOrder(root, func);
}
References Bst< T >::inOrder(), and Bst< T >::root.
Referenced by WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), TestDuplicateInsert(), and TestInOrderTraversal().
Insert()
template<class T > void Bst< T >::Insert (const T & value)
Inserts a value into the BST.
Duplicate values are ignored and not inserted.
Parameters
value The value to insert.
Definition at line 232 of file Bst.h.
{
    root = insert(root, value);
}
References Bst< T >::insert(), and Bst< T >::root.
Referenced by InsertMiddle(), TestAssignmentOperator(), TestCopyConstructor(), TestDeleteLeaf(), TestDeleteOneChild(), TestDeleteRoot(), TestDeleteTree(), TestDeleteTwoChildren(), TestDuplicateInsert(), TestInOrderTraversal(), TestInsertAndSearch(), TestInvariantChecker(), TestPostOrderTraversal(), and TestPreOrderTraversal().
insert()
template<class T > Bst< T >::Node * Bst< T >::insert (Node * node, const T & value) private
Recursive insert helper.
Parameters
node Current subtree root.
value Value to insert.
Returns
Updated subtree root pointer.
Definition at line 238 of file Bst.h.
{
    if (node == nullptr)
    {
        node = new Node{value, nullptr, nullptr};
    }
    else if (value < node->data)
    {
        node->left = insert(node->left, value);
    }
    else if (value > node->data)
    {
        node->right = insert(node->right, value);
    }
    return node;
}
References Bst< T >::insert().
Referenced by Bst< T >::Insert(), and Bst< T >::insert().
operator=()
template<class T > Bst< T > & Bst< T >::operator= (const Bst< T > & other)
Copy assignment operator.
Replaces the contents of this BST with a deep copy of other.
Parameters
other Tree to copy from.
Returns
Reference to this instance.
Definition at line 221 of file Bst.h.
{
    if (this != &other)  // protect against self-assignment
    {
        deleteTree(root);
        root = copyTree(other.root);
    }
    return *this;
}
References Bst< T >::copyTree(), Bst< T >::deleteTree(), and Bst< T >::root.
Referenced by WeatherLog::LoadData(), and TestAssignmentOperator().
postOrder()
template<class T > void Bst< T >::postOrder (const Node * node, void(*)(const T &) func) const private
Recursive post-order traversal helper.
Definition at line 399 of file Bst.h.
{
    if (node)
    {
        postOrder(node->left, func);
        postOrder(node->right, func);
        func(node->data);
    }
}
References Bst< T >::postOrder().
Referenced by Bst< T >::postOrder(), and Bst< T >::PostOrder().
PostOrder()
template<class T > void Bst< T >::PostOrder (void(*)(const T &) func) const
Performs a post-order traversal.
Order: Left Right Root
Parameters
func Function applied to each visited node's value.
Definition at line 393 of file Bst.h.
{
    postOrder(root, func);
}
References Bst< T >::postOrder(), and Bst< T >::root.
Referenced by TestPostOrderTraversal().
preOrder()
template<class T > void Bst< T >::preOrder (const Node * node, void(*)(const T &) func) const private
Recursive pre-order traversal helper.
Definition at line 382 of file Bst.h.
{
    if (node)
    {
        func(node->data);
        preOrder(node->left, func);
        preOrder(node->right, func);
    }
}
References Bst< T >::preOrder().
Referenced by Bst< T >::preOrder(), and Bst< T >::PreOrder().
PreOrder()
template<class T > void Bst< T >::PreOrder (void(*)(const T &) func) const
Performs a pre-order traversal.
Order: Root Left Right
Parameters
func Function applied to each visited node's value.
Definition at line 376 of file Bst.h.
{
    preOrder(root, func);
}
References Bst< T >::preOrder(), and Bst< T >::root.
Referenced by TestPreOrderTraversal().
Search()
template<class T > bool Bst< T >::Search (const T & value) const
Searches for a value in the BST.
Parameters
value The value to locate.
Returns
True if the value exists, false otherwise.
Definition at line 256 of file Bst.h.
{
    return search(root, value);
}
References Bst< T >::root, and Bst< T >::search().
Referenced by TestAssignmentOperator(), TestCopyConstructor(), TestDeleteLeaf(), TestDeleteOneChild(), TestDeleteRoot(), TestDeleteTree(), TestDeleteTwoChildren(), and TestInsertAndSearch().
search()
template<class T > bool Bst< T >::search (Node * node, const T & value) const private
Recursive search helper.
Parameters
node Current subtree root.
value Value to locate.
Returns
True if the value is found.
Definition at line 262 of file Bst.h.
{
    if (node == nullptr)
    {
        return false;
    }
    else if (value == node->data)
    {
        return true;
    }
    else if (value < node->data)
    {
        return search(node->left, value);
    }
    else
    {
        return search(node->right, value);
    }
}
References Bst< T >::search().
Referenced by Bst< T >::Search(), and Bst< T >::search().
Member Data Documentation
root
template<class T > Node* Bst< T >::root private
Pointer to the root of the BST.
Definition at line 132 of file Bst.h.
Referenced by Bst< T >::Bst(), Bst< T >::Bst(), Bst< T >::DeleteNode(), Bst< T >::DeleteTree(), Bst< T >::InOrder(), Bst< T >::Insert(), Bst< T >::operator=(), Bst< T >::PostOrder(), Bst< T >::PreOrder(), Bst< T >::Search(), and Bst< T >::~Bst().
The documentation for this class was generated from the following file:
A2/Assignment2/Code/Bst.h