Assignment 2: Vector< T > Class Template Reference
Vector< T > Class Template Reference
A template class that implements a dynamic array (vector)
#include <EncapVect.h>
Public Member Functions
Vector ()
Constructs an empty Vector.
Vector (int n)
Constructs a Vector with a preallocated size.
bool Add (const T &value)
Appends a new value to the end of the vector.
bool Insert (int index, const T &value)
Inserts an element at a given index.
bool Delete (int index)
Deletes the element at a given index.
int GetSize () const
Returns the number of elements currently stored.
bool IsEmpty () const
Checks whether the vector is empty.
void Clear ()
Removes all elements from the vector.
void PushBack (const T &value)
Appends an element to the end of the vector.
T & operator[] (int index)
Provides indexed access to elements with bounds checking.
const T & operator[] (int index) const
Provides const indexed access to elements with bounds checking.
Vector ()
Default constructor Initializes the vector with an initial capacity.
Vector (int n)
Parameterized constructor.
Vector (const Vector< T > &other)
Copy constructor.
~Vector ()
Destructor Frees dynamically allocated memory.
Vector< T > & operator= (const Vector< T > &other)
Assignment operator.
bool Insert (int index, const T &value)
Inserts a value at a given index.
bool Delete (int index)
Deletes the element at a given index.
int GetSize () const
Returns the number of elements in the vector.
T & operator[] (int index)
Access element at a given index.
const T & operator[] (int index) const
Access element at a given index (const version)
Private Member Functions
void Resize ()
Resizes the vector if it is more than half full.
Private Attributes
vector< T > m_data
Underlying storage container.
T * m_array
int m_size
int m_capacity
Detailed Description
template<class T>
class Vector< T >
A template class that implements a dynamic array (vector)
A simplified wrapper around std::vector providing controlled access and basic operations.
Template Parameters
T Type of elements stored in the vector
This templated Vector class supports dynamic resizing, element insertion, deletion, indexed access with bounds checking, and size queries. It is intentionally limited compared to std::vector to align with unit-testing and teaching requirements of the assignment.
Template Parameters
T Type of elements stored in the vector.
Definition at line 23 of file EncapVect.h.
Constructor & Destructor Documentation
Vector() [1/5]
template<class T > Vector< T >::Vector ()
Constructs an empty Vector.
Definition at line 110 of file EncapVect.h.
                  : m_data()
{
}
Referenced by WeatherLog::LoadData().
Vector() [2/5]
template<class T > Vector< T >::Vector (int n)
Constructs a Vector with a preallocated size.
Parameters
n Number of elements to allocate. Values are default-initialized.
Definition at line 115 of file EncapVect.h.
                       : m_data()
{
    if (n > 0)
    {
        m_data.resize(n);
    }
}
Vector() [3/5]
template<class T > Vector< T >::Vector ()
Default constructor Initializes the vector with an initial capacity.
Vector() [4/5]
template<class T > Vector< T >::Vector (int n)
Parameterized constructor.
Parameters
n Initial capacity of the vector
Vector() [5/5]
template<class T > Vector< T >::Vector (const Vector< T > & other)
Copy constructor.
Parameters
other Vector to copy from
Definition at line 116 of file Vector.h.
{
    m_size = other.m_size;
    m_capacity = other.m_capacity;
    if(m_capacity > 0)
    {
        m_array = new T[m_capacity];
        for(int i = 0; i < m_size; i++)
        {
            m_array[i] = other.m_array[i];
        }
    }
    else
        m_array = nullptr;
}
References Vector< T >::m_array, Vector< T >::m_capacity, and Vector< T >::m_size.
Referenced by testIntVec().
~Vector()
template<class T > Vector< T >::~Vector ()
Destructor Frees dynamically allocated memory.
Definition at line 134 of file Vector.h.
{
    delete[] m_array;
}
References Vector< T >::m_array.
Member Function Documentation
Add()
template<class T > bool Vector< T >::Add (const T & value)
Appends a new value to the end of the vector.
Parameters
value Element to append.
Returns
True if the operation succeeded, false if memory allocation failed.
Definition at line 124 of file EncapVect.h.
{
    try
    {
        m_data.push_back(value);
        return true;
    }
    catch (...)
    {
        return false;
    }
}
Clear()
template<class T > void Vector< T >::Clear ()
Removes all elements from the vector.
Definition at line 207 of file EncapVect.h.
{
    m_data.clear();
}
Delete() [1/2]
template<class T > bool Vector< T >::Delete (int index)
Deletes the element at a given index.
Parameters
index Index of the element to remove.
Returns
True if deletion succeeded, false if index was invalid.
Definition at line 163 of file EncapVect.h.
{
    if (index < 0 || index >= m_data.size())
    {
        return false;
    }
    m_data.erase(m_data.begin() + index);
    return true;
}
Referenced by DeleteTest(), testDateVecRef(), testDateVecValue(), and testIntVec().
Delete() [2/2]
template<class T > bool Vector< T >::Delete (int index)
Deletes the element at a given index.
Parameters
index Position to delete (0-based)
Returns
true if deletion succeeded, false if index invalid
GetSize() [1/2]
template<class T > int Vector< T >::GetSize () const
Returns the number of elements currently stored.
Returns
Size of the vector.
Definition at line 195 of file EncapVect.h.
{
    return m_data.size();
}
Referenced by AssignTest(), CollectRecNode(), CopyTest(), DefaultTest(), DeleteTest(), WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), InsertTest(), WeatherLog::LoadData(), main(), MeanAbsoluteDeviation(), sPCC(), testDateVecRef(), testDateVecValue(), and testIntVec().
GetSize() [2/2]
template<class T > int Vector< T >::GetSize () const
Returns the number of elements in the vector.
Returns
Current size of the vector
Insert() [1/2]
template<class T > bool Vector< T >::Insert (int index, const T & value)
Inserts an element at a given index.
Elements at and after the index are shifted to the right.
Parameters
index Position to insert at (0 index size).
value Element to insert.
Returns
True if index was valid and insertion succeeded, otherwise false.
Definition at line 144 of file EncapVect.h.
{
    if (index < 0 || index > m_data.size())
    {
        return false;
    }
    try
    {
        m_data.insert(m_data.begin() + index, value);
        return true;
    }
    catch (...)
    {
        return false;
    }
}
Referenced by CollectRecNode(), WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), InsertTest(), WeatherLog::LoadData(), testDateVecRef(), testDateVecValue(), and testIntVec().
Insert() [2/2]
template<class T > bool Vector< T >::Insert (int index, const T & value)
Inserts a value at a given index.
Parameters
index Position to insert at (0-based)
value Value to insert
Returns
true if insertion succeeded, false if index invalid
IsEmpty()
template<class T > bool Vector< T >::IsEmpty () const
Checks whether the vector is empty.
Returns
True if no elements exist, false otherwise.
Definition at line 201 of file EncapVect.h.
{
    return m_data.empty();
}
operator=()
template<class T > Vector< T > & Vector< T >::operator= (const Vector< T > & other)
Assignment operator.
Parameters
other Vector to assign from
Returns
Reference to this vector
Definition at line 140 of file Vector.h.
{
    if(this == &other)
    {
        return *this;
    }
    delete[] m_array;
    m_size = other.m_size;
    m_capacity = other.m_capacity;
    if(m_capacity > 0)
    {
        m_array = new T[m_capacity];
        for(int i = 0; i < m_size; i++)
        {
            m_array[i] = other.m_array[i];
        }
    }
    else
    {
        m_array = nullptr;
    }
    return *this;
}
References Vector< T >::m_array, Vector< T >::m_capacity, and Vector< T >::m_size.
Referenced by testIntVec().
operator[]() [1/4]
template<class T > T & Vector< T >::operator[] (int index)
Provides indexed access to elements with bounds checking.
Parameters
index Index of the requested element.
Returns
Reference to the element at the specified index.
Exceptions
out_of_range If index is invalid.
Definition at line 175 of file EncapVect.h.
{
    if (index < 0 || index >= m_data.size())
    {
        throw out_of_range("Index out of bounds");
    }
    return m_data[index];
}
Referenced by AccessTest(), AssignTest(), CopyTest(), DeleteTest(), WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), InsertMiddle(), InsertTest(), WeatherLog::LoadData(), main(), testDateVecRef(), testDateVecValue(), and testIntVec().
operator[]() [2/4]
template<class T > T & Vector< T >::operator[] (int index)
Access element at a given index.
Parameters
index Position of the element
Returns
Reference to element at index
Exceptions
out_of_range if index is invalid
operator[]() [3/4]
template<class T > const T & Vector< T >::operator[] (int index) const
Provides const indexed access to elements with bounds checking.
Parameters
index Index of the requested element.
Returns
Const reference to the element at the specified index.
Exceptions
out_of_range If index is invalid.
Definition at line 185 of file EncapVect.h.
{
    if (index < 0 || index >= m_data.size())
    {
        throw out_of_range("Index out of bounds");
    }
    return m_data[index];
}
Referenced by MeanAbsoluteDeviation(), and sPCC().
operator[]() [4/4]
template<class T > const T & Vector< T >::operator[] (int index) const
Access element at a given index (const version)
Parameters
index Position of the element
Returns
Const reference to element at index
Exceptions
out_of_range if index is invalid
PushBack()
template<class T > void Vector< T >::PushBack (const T & value)
Appends an element to the end of the vector.
Unlike Add(), this method assumes no allocation failure.
Parameters
value Element to append.
Definition at line 138 of file EncapVect.h.
{
    m_data.push_back(value);
}
Resize()
template<class T > void Vector< T >::Resize () private
Resizes the vector if it is more than half full.
Definition at line 169 of file Vector.h.
{
    if(m_size > m_capacity / 2)
    {
        int newCapacity = (m_capacity == 0) ? 1 : m_capacity * 2;
        T* newArray = new T[newCapacity];
        for(int i = 0; i < m_size; i++)
        {
            newArray[i] = m_array[i];
        }
        delete[] m_array;
        m_array = nullptr;
        m_array = newArray;
        m_capacity = newCapacity;
    }
}
References Vector< T >::m_array, Vector< T >::m_capacity, and Vector< T >::m_size.
Member Data Documentation
m_array
template<class T > T* Vector< T >::m_array private
Pointer to dynamic array
Definition at line 89 of file Vector.h.
Referenced by Vector< T >::operator=(), Vector< T >::Resize(), Vector< T >::Vector(), and Vector< T >::~Vector().
m_capacity
template<class T > int Vector< T >::m_capacity private
Allocated capacity
Definition at line 91 of file Vector.h.
Referenced by Vector< T >::operator=(), Vector< T >::Resize(), and Vector< T >::Vector().
m_data
template<class T > vector<T> Vector< T >::m_data private
Underlying storage container.
Definition at line 105 of file EncapVect.h.
m_size
template<class T > int Vector< T >::m_size private
Number of elements stored
Definition at line 90 of file Vector.h.
Referenced by Vector< T >::operator=(), Vector< T >::Resize(), and Vector< T >::Vector().
The documentation for this class was generated from the following files:
A2/Assignment2/Code/EncapVect.h
A2/Assignment2/Code/Vector.h