Assignment 2: WeatherRec Class Reference
WeatherRec Class Reference
Represents a single weather observation.
#include <WeatherRec.h>
Public Member Functions
WeatherRec ()
Default constructor.
WeatherRec (const Date &d, const Time &t, float speed, float solarRad, float ambAirTemp)
Parameterized constructor for creating a complete weather record.
const Date & GetDate () const
Returns the observation date.
const Time & GetTime () const
Returns the observation time.
int GetMonth () const
Returns the month of the observation.
int GetYear () const
Returns the year of the observation.
float GetSpeed () const
Returns the wind speed in m/s.
float GetSolarRad () const
Returns the solar radiation in W/m².
float GetAmbAirTemp () const
Returns the ambient air temperature in °C.
void SetDate (const Date &d)
Sets the observation date.
void SetTime (const Time &t)
Sets the observation time.
void SetSpeed (float speed)
Sets the wind speed in m/s.
void SetSolarRad (float solarRad)
Sets the solar radiation in W/m².
void SetAmbAirTemp (float ambAirTemp)
Sets the air temperature in °C.
DateTimeKey GetDateTimeKey () const
Generates a sortable key combining date and time.
Private Attributes
Date m_date
Time m_time
float m_speed
float m_solarRad
float m_airTemp
Detailed Description
Represents a single weather observation.
A WeatherRec object stores:
The date of observation
The time of observation
Wind speed (m/s)
Solar radiation (W/m²)
Ambient air temperature (°C)
Each record can generate a DateTimeKey, which provides a unique and fully sortable timestamp suitable for use as the key in a BST.
Definition at line 25 of file WeatherRec.h.
Constructor & Destructor Documentation
WeatherRec() [1/2]
WeatherRec::WeatherRec ()
Default constructor.
Initializes:
Date and Time to their default-constructed values
Wind speed, solar radiation, and temperature to 0.0
Definition at line 9 of file WeatherRec.cpp.
{
    m_speed = 0.0f;
    m_solarRad = 0.0f;
    m_airTemp = 0.0f;
}
References m_airTemp, m_solarRad, and m_speed.
WeatherRec() [2/2]
WeatherRec::WeatherRec (const Date & d, const Time & t, float speed, float solarRad, float ambAirTemp)
Parameterized constructor for creating a complete weather record.
Parameters
d Date of the observation.
t Time of the observation.
speed Wind speed in m/s.
solarRad Solar radiation in W/m².
ambAirTemp Ambient air temperature in °C.
Definition at line 17 of file WeatherRec.cpp.
{
    m_date = d;
    m_time = t;
    m_speed = speed;
    m_solarRad = solarRad;
    m_airTemp = ambAirTemp;
}
References m_airTemp, m_date, m_solarRad, m_speed, and m_time.
Referenced by WeatherLog::LoadData().
Member Function Documentation
GetAmbAirTemp()
float WeatherRec::GetAmbAirTemp () const
Returns the ambient air temperature in °C.
Definition at line 63 of file WeatherRec.cpp.
{
    return m_airTemp;
}
References m_airTemp.
Referenced by WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), and operator<<().
GetDate()
const Date & WeatherRec::GetDate () const
Returns the observation date.
Definition at line 27 of file WeatherRec.cpp.
{
    return m_date;
}
References m_date.
Referenced by operator<<(), and RecNode::RecNode().
GetDateTimeKey()
DateTimeKey WeatherRec::GetDateTimeKey () const
Generates a sortable key combining date and time.
The DateTimeKey sorts in this order:
Year
Month
Day
Hour
Minute
Returns
A DateTimeKey object representing the timestamp of this record.
Definition at line 99 of file WeatherRec.cpp.
{
    return DateTimeKey(m_date, m_time);
}
References DateTimeKey::DateTimeKey(), m_date, and m_time.
GetMonth()
int WeatherRec::GetMonth () const
Returns the month of the observation.
Returns
Integer in the range 1–12.
Definition at line 39 of file WeatherRec.cpp.
{
    return m_date.GetMonth();
}
References Date::GetMonth(), and m_date.
GetSolarRad()
float WeatherRec::GetSolarRad () const
Returns the solar radiation in W/m².
Definition at line 57 of file WeatherRec.cpp.
{
    return m_solarRad;
}
References m_solarRad.
Referenced by WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), and operator<<().
GetSpeed()
float WeatherRec::GetSpeed () const
Returns the wind speed in m/s.
Definition at line 51 of file WeatherRec.cpp.
{
    return m_speed;
}
References m_speed.
Referenced by WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), and operator<<().
GetTime()
const Time & WeatherRec::GetTime () const
Returns the observation time.
Definition at line 33 of file WeatherRec.cpp.
{
    return m_time;
}
References m_time.
Referenced by operator<<(), and RecNode::RecNode().
GetYear()
int WeatherRec::GetYear () const
Returns the year of the observation.
Definition at line 45 of file WeatherRec.cpp.
{
    return m_date.GetYear();
}
References Date::GetYear(), and m_date.
SetAmbAirTemp()
void WeatherRec::SetAmbAirTemp (float ambAirTemp)
Sets the air temperature in °C.
Definition at line 93 of file WeatherRec.cpp.
{
    m_airTemp = ambAirTemp;
}
References m_airTemp.
SetDate()
void WeatherRec::SetDate (const Date & d)
Sets the observation date.
Definition at line 69 of file WeatherRec.cpp.
{
    m_date = d;
}
References m_date.
SetSolarRad()
void WeatherRec::SetSolarRad (float solarRad)
Sets the solar radiation in W/m².
Definition at line 87 of file WeatherRec.cpp.
{
    m_solarRad = solarRad;
}
References m_solarRad.
SetSpeed()
void WeatherRec::SetSpeed (float speed)
Sets the wind speed in m/s.
Definition at line 81 of file WeatherRec.cpp.
{
    m_speed = speed;
}
References m_speed.
SetTime()
void WeatherRec::SetTime (const Time & t)
Sets the observation time.
Definition at line 75 of file WeatherRec.cpp.
{
    m_time = t;
}
References m_time.
Member Data Documentation
m_airTemp
float WeatherRec::m_airTemp private
Ambient air temperature (°C).
Definition at line 109 of file WeatherRec.h.
Referenced by GetAmbAirTemp(), SetAmbAirTemp(), WeatherRec(), and WeatherRec().
m_date
Date WeatherRec::m_date private
Observation date.
Definition at line 105 of file WeatherRec.h.
Referenced by GetDate(), GetDateTimeKey(), GetMonth(), GetYear(), SetDate(), and WeatherRec().
m_solarRad
float WeatherRec::m_solarRad private
Solar radiation (W/m²).
Definition at line 108 of file WeatherRec.h.
Referenced by GetSolarRad(), SetSolarRad(), WeatherRec(), and WeatherRec().
m_speed
float WeatherRec::m_speed private
Wind speed (m/s).
Definition at line 107 of file WeatherRec.h.
Referenced by GetSpeed(), SetSpeed(), WeatherRec(), and WeatherRec().
m_time
Time WeatherRec::m_time private
Observation time.
Definition at line 106 of file WeatherRec.h.
Referenced by GetDateTimeKey(), GetTime(), SetTime(), and WeatherRec().
The documentation for this class was generated from the following files:
A2/Assignment2/Code/WeatherRec.h
A2/Assignment2/Code/WeatherRec.cpp