Assignment 2: RecNode Struct Reference
RecNode Struct Reference
Node wrapper storing a WeatherRec and its sortable DateTimeKey for BST usage.
#include <RecNode.h>
Public Member Functions
RecNode ()=default
Default constructor.
RecNode (const WeatherRec &w)
Constructs a RecNode from a WeatherRec.
bool operator< (const RecNode &other) const
Comparison operator for BST ordering.
bool operator> (const RecNode &other) const
Comparison operator for BST ordering.
bool operator== (const RecNode &other) const
Equality comparison based on the DateTimeKey.
Public Attributes
DateTimeKey key
WeatherRec rec
Detailed Description
Node wrapper storing a WeatherRec and its sortable DateTimeKey for BST usage.
RecNode acts as the element type stored in the binary search tree. Each node contains a WeatherRec and an associated DateTimeKey that determines ordering within the BST. Comparison operators use only the DateTimeKey, ensuring that tree operations are based strictly on chronological order.
Definition at line 16 of file RecNode.h.
Constructor & Destructor Documentation
RecNode() [1/2]
RecNode::RecNode () default
Default constructor.
Leaves members default-initialized. Intended mainly for container compatibility.
RecNode() [2/2]
RecNode::RecNode (const WeatherRec & w) inline
Constructs a RecNode from a WeatherRec.
Parameters
w The WeatherRec from which to build this node.
Generates a DateTimeKey using the record's date and time, ensuring that RecNode objects can be placed in the BST in chronological order.
Definition at line 35 of file RecNode.h.
        : key(w.GetDate(), w.GetTime()), rec(w)
    {
    }
References DateTimeKey::DateTimeKey(), WeatherRec::GetDate(), WeatherRec::GetTime(), key, and rec.
Referenced by WeatherLog::LoadData().
Member Function Documentation
operator<()
bool RecNode::operator< (const RecNode & other) const inline
Comparison operator for BST ordering.
Parameters
other Another RecNode to compare against.
Returns
True if this node's key is earlier than the other's key.
Definition at line 45 of file RecNode.h.
    {
        return key < other.key;
    }
References key, and DateTimeKey::operator<().
operator==()
bool RecNode::operator== (const RecNode & other) const inline
Equality comparison based on the DateTimeKey.
Parameters
other Another RecNode to compare against.
Returns
True if both nodes share the same DateTimeKey.
Definition at line 65 of file RecNode.h.
    {
        return key == other.key;
    }
References key, and DateTimeKey::operator==().
operator>()
bool RecNode::operator> (const RecNode & other) const inline
Comparison operator for BST ordering.
Parameters
other Another RecNode to compare against.
Returns
True if this node's key is later than the other's key.
Definition at line 55 of file RecNode.h.
    {
        return key > other.key;
    }
References key, and DateTimeKey::operator>().
Member Data Documentation
key
DateTimeKey RecNode::key
Chronological key generated from the record's date and time.
Definition at line 18 of file RecNode.h.
Referenced by operator<(), operator==(), operator>(), and RecNode().
rec
WeatherRec RecNode::rec
Full weather record stored in this node.
Definition at line 19 of file RecNode.h.
Referenced by WeatherLog::DisplayAvgSpeed(), WeatherLog::DisplayAvgTempSD(), WeatherLog::DisplaySPCC(), WeatherLog::DisplaySpeedTempSolarRadWithMAD(), and RecNode().
The documentation for this struct was generated from the following file:
A2/Assignment2/Code/RecNode.h