Assignment 2: DateTimeKey Struct Reference
DateTimeKey Struct Reference
A sortable key combining Date and Time for BST indexing.
#include <DateTimeKey.h>
Public Member Functions
DateTimeKey ()
Default constructor.
DateTimeKey (const Date &d, const Time &t)
Constructs a key directly from a Date and Time object.
bool operator< (const DateTimeKey &other) const
Strict weak ordering based on chronological time.
bool operator> (const DateTimeKey &other) const
Reverse chronological comparison.
bool operator== (const DateTimeKey &other) const
Equality comparison.
Public Attributes
int year
Year component.
int month
Month component (1–12)
int day
Day component (1–31)
int hour
Hour component (0–23)
int minute
Minute component (0–59)
Detailed Description
A sortable key combining Date and Time for BST indexing.
This structure converts a Date and Time into a strict ordering key used by the BST when inserting or searching for weather records.
Ordering priority:
Year
Month
Day
Hour
Minute
This provides a unique chronological ordering for every WeatherRec entry, ensuring deterministic placement inside the binary search tree.
Definition at line 24 of file DateTimeKey.h.
Constructor & Destructor Documentation
DateTimeKey() [1/2]
DateTimeKey::DateTimeKey () inline
Default constructor.
Initializes all fields to zero. Primarily used for placeholder keys.
Definition at line 38 of file DateTimeKey.h.
        : year(0), month(0), day(0), hour(0), minute(0)
    {
    }
References day, hour, minute, month, and year.
DateTimeKey() [2/2]
DateTimeKey::DateTimeKey (const Date & d, const Time & t) inline
Constructs a key directly from a Date and Time object.
Parameters
d Date component.
t Time component.
Definition at line 48 of file DateTimeKey.h.
        : year(d.GetYear()),
          month(d.GetMonth()),
          day(d.GetDay()),
          hour(t.GetHours()),
          minute(t.GetMinutes())
    {
    }
References day, Date::GetDay(), Time::GetHours(), Time::GetMinutes(), Date::GetMonth(), Date::GetYear(), hour, minute, month, and year.
Referenced by WeatherRec::GetDateTimeKey(), RecNode::RecNode(), TestEquality(), and TestOrdering().
Member Function Documentation
operator<()
bool DateTimeKey::operator< (const DateTimeKey & other) const inline
Strict weak ordering based on chronological time.
Used by the BST to determine left/right placement.
Parameters
other Key to compare with.
Returns
True if this key is chronologically earlier than other.
Definition at line 65 of file DateTimeKey.h.
    {
        if (year != other.year)
        {
            return year < other.year;
        }
        if (month != other.month)
        {
            return month < other.month;
        }
        if (day != other.day)
        {
            return day < other.day;
        }
        if (hour != other.hour)
        {
            return hour < other.hour;
        }
        return minute < other.minute;
    }
References day, hour, minute, month, and year.
Referenced by RecNode::operator<(), operator>(), TestEquality(), and TestOrdering().
operator==()
bool DateTimeKey::operator== (const DateTimeKey & other) const inline
Equality comparison.
Parameters
other Key to compare with.
Returns
True if all date/time components match exactly.
Definition at line 101 of file DateTimeKey.h.
    {
        return year   == other.year &&
               month  == other.month &&
               day    == other.day &&
               hour   == other.hour &&
               minute == other.minute;
    }
References day, hour, minute, month, and year.
Referenced by RecNode::operator==(), and TestEquality().
operator>()
bool DateTimeKey::operator> (const DateTimeKey & other) const inline
Reverse chronological comparison.
Parameters
other Key to compare with.
Returns
True if this key is later than other.
Definition at line 91 of file DateTimeKey.h.
    {
        return other < *this;
    }
References operator<().
Referenced by RecNode::operator>(), TestEquality(), and TestOrdering().
Member Data Documentation
day
int DateTimeKey::day
Day component (1–31)
Definition at line 29 of file DateTimeKey.h.
Referenced by DateTimeKey(), DateTimeKey(), operator<(), and operator==().
hour
int DateTimeKey::hour
Hour component (0–23)
Definition at line 30 of file DateTimeKey.h.
Referenced by DateTimeKey(), DateTimeKey(), operator<(), and operator==().
minute
int DateTimeKey::minute
Minute component (0–59)
Definition at line 31 of file DateTimeKey.h.
Referenced by DateTimeKey(), DateTimeKey(), operator<(), and operator==().
month
int DateTimeKey::month
Month component (1–12)
Definition at line 28 of file DateTimeKey.h.
Referenced by DateTimeKey(), DateTimeKey(), operator<(), and operator==().
year
int DateTimeKey::year
Year component.
Definition at line 27 of file DateTimeKey.h.
Referenced by DateTimeKey(), DateTimeKey(), operator<(), and operator==().
The documentation for this struct was generated from the following file:
A2/Assignment2/Code/DateTimeKey.h